name: Build binaries and upload as artifacts

on: workflow_dispatch

jobs:

  release:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    timeout-minutes: 30

    strategy:
      matrix:
        # This is all run on macos so artifacting is contained to one folder
        os: [macos-latest]
        node-version: [16.x]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Install Node.js, npm and yarn
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Run build script
        run: node .github/build-binaries.js

      - name: Artifact binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            binaries/*.exe

            binaries/*.dmg
            binaries/*.pkg

            binaries/*.AppImage
            binaries/*.deb
            binaries/*.rpm
          if-no-files-found: error
